# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_sofaswig', [dirname(__file__)])
        except ImportError:
            import _sofaswig
            return _sofaswig
        if fp is not None:
            try:
                _mod = imp.load_module('_sofaswig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _sofaswig = swig_import_helper()
    del swig_import_helper
else:
    import _sofaswig
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class doublep(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, doublep, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doublep, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _sofaswig.new_doublep()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sofaswig.delete_doublep
    __del__ = lambda self : None;
    def assign(self, *args): return _sofaswig.doublep_assign(self, *args)
    def value(self): return _sofaswig.doublep_value(self)
    def cast(self): return _sofaswig.doublep_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _sofaswig.doublep_frompointer
    if _newclass:frompointer = staticmethod(_sofaswig.doublep_frompointer)
doublep_swigregister = _sofaswig.doublep_swigregister
doublep_swigregister(doublep)

def doublep_frompointer(*args):
  return _sofaswig.doublep_frompointer(*args)
doublep_frompointer = _sofaswig.doublep_frompointer

class floatp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, floatp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, floatp, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _sofaswig.new_floatp()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sofaswig.delete_floatp
    __del__ = lambda self : None;
    def assign(self, *args): return _sofaswig.floatp_assign(self, *args)
    def value(self): return _sofaswig.floatp_value(self)
    def cast(self): return _sofaswig.floatp_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _sofaswig.floatp_frompointer
    if _newclass:frompointer = staticmethod(_sofaswig.floatp_frompointer)
floatp_swigregister = _sofaswig.floatp_swigregister
floatp_swigregister(floatp)

def floatp_frompointer(*args):
  return _sofaswig.floatp_frompointer(*args)
floatp_frompointer = _sofaswig.floatp_frompointer

class intp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intp, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _sofaswig.new_intp()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sofaswig.delete_intp
    __del__ = lambda self : None;
    def assign(self, *args): return _sofaswig.intp_assign(self, *args)
    def value(self): return _sofaswig.intp_value(self)
    def cast(self): return _sofaswig.intp_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _sofaswig.intp_frompointer
    if _newclass:frompointer = staticmethod(_sofaswig.intp_frompointer)
intp_swigregister = _sofaswig.intp_swigregister
intp_swigregister(intp)

def intp_frompointer(*args):
  return _sofaswig.intp_frompointer(*args)
intp_frompointer = _sofaswig.intp_frompointer

class doubleArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, doubleArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doubleArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sofaswig.new_doubleArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sofaswig.delete_doubleArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _sofaswig.doubleArray___getitem__(self, *args)
    def __setitem__(self, *args): return _sofaswig.doubleArray___setitem__(self, *args)
    def cast(self): return _sofaswig.doubleArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _sofaswig.doubleArray_frompointer
    if _newclass:frompointer = staticmethod(_sofaswig.doubleArray_frompointer)
doubleArray_swigregister = _sofaswig.doubleArray_swigregister
doubleArray_swigregister(doubleArray)

def doubleArray_frompointer(*args):
  return _sofaswig.doubleArray_frompointer(*args)
doubleArray_frompointer = _sofaswig.doubleArray_frompointer

class floatArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, floatArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, floatArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sofaswig.new_floatArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sofaswig.delete_floatArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _sofaswig.floatArray___getitem__(self, *args)
    def __setitem__(self, *args): return _sofaswig.floatArray___setitem__(self, *args)
    def cast(self): return _sofaswig.floatArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _sofaswig.floatArray_frompointer
    if _newclass:frompointer = staticmethod(_sofaswig.floatArray_frompointer)
floatArray_swigregister = _sofaswig.floatArray_swigregister
floatArray_swigregister(floatArray)

def floatArray_frompointer(*args):
  return _sofaswig.floatArray_frompointer(*args)
floatArray_frompointer = _sofaswig.floatArray_frompointer

class intArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sofaswig.new_intArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sofaswig.delete_intArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _sofaswig.intArray___getitem__(self, *args)
    def __setitem__(self, *args): return _sofaswig.intArray___setitem__(self, *args)
    def cast(self): return _sofaswig.intArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _sofaswig.intArray_frompointer
    if _newclass:frompointer = staticmethod(_sofaswig.intArray_frompointer)
intArray_swigregister = _sofaswig.intArray_swigregister
intArray_swigregister(intArray)

def intArray_frompointer(*args):
  return _sofaswig.intArray_frompointer(*args)
intArray_frompointer = _sofaswig.intArray_frompointer

class iauASTROM(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, iauASTROM, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, iauASTROM, name)
    __repr__ = _swig_repr
    __swig_setmethods__["pmt"] = _sofaswig.iauASTROM_pmt_set
    __swig_getmethods__["pmt"] = _sofaswig.iauASTROM_pmt_get
    if _newclass:pmt = _swig_property(_sofaswig.iauASTROM_pmt_get, _sofaswig.iauASTROM_pmt_set)
    __swig_setmethods__["eb"] = _sofaswig.iauASTROM_eb_set
    __swig_getmethods__["eb"] = _sofaswig.iauASTROM_eb_get
    if _newclass:eb = _swig_property(_sofaswig.iauASTROM_eb_get, _sofaswig.iauASTROM_eb_set)
    __swig_setmethods__["eh"] = _sofaswig.iauASTROM_eh_set
    __swig_getmethods__["eh"] = _sofaswig.iauASTROM_eh_get
    if _newclass:eh = _swig_property(_sofaswig.iauASTROM_eh_get, _sofaswig.iauASTROM_eh_set)
    __swig_setmethods__["em"] = _sofaswig.iauASTROM_em_set
    __swig_getmethods__["em"] = _sofaswig.iauASTROM_em_get
    if _newclass:em = _swig_property(_sofaswig.iauASTROM_em_get, _sofaswig.iauASTROM_em_set)
    __swig_setmethods__["v"] = _sofaswig.iauASTROM_v_set
    __swig_getmethods__["v"] = _sofaswig.iauASTROM_v_get
    if _newclass:v = _swig_property(_sofaswig.iauASTROM_v_get, _sofaswig.iauASTROM_v_set)
    __swig_setmethods__["bm1"] = _sofaswig.iauASTROM_bm1_set
    __swig_getmethods__["bm1"] = _sofaswig.iauASTROM_bm1_get
    if _newclass:bm1 = _swig_property(_sofaswig.iauASTROM_bm1_get, _sofaswig.iauASTROM_bm1_set)
    __swig_setmethods__["bpn"] = _sofaswig.iauASTROM_bpn_set
    __swig_getmethods__["bpn"] = _sofaswig.iauASTROM_bpn_get
    if _newclass:bpn = _swig_property(_sofaswig.iauASTROM_bpn_get, _sofaswig.iauASTROM_bpn_set)
    __swig_setmethods__["along"] = _sofaswig.iauASTROM_along_set
    __swig_getmethods__["along"] = _sofaswig.iauASTROM_along_get
    if _newclass:along = _swig_property(_sofaswig.iauASTROM_along_get, _sofaswig.iauASTROM_along_set)
    __swig_setmethods__["phi"] = _sofaswig.iauASTROM_phi_set
    __swig_getmethods__["phi"] = _sofaswig.iauASTROM_phi_get
    if _newclass:phi = _swig_property(_sofaswig.iauASTROM_phi_get, _sofaswig.iauASTROM_phi_set)
    __swig_setmethods__["xpl"] = _sofaswig.iauASTROM_xpl_set
    __swig_getmethods__["xpl"] = _sofaswig.iauASTROM_xpl_get
    if _newclass:xpl = _swig_property(_sofaswig.iauASTROM_xpl_get, _sofaswig.iauASTROM_xpl_set)
    __swig_setmethods__["ypl"] = _sofaswig.iauASTROM_ypl_set
    __swig_getmethods__["ypl"] = _sofaswig.iauASTROM_ypl_get
    if _newclass:ypl = _swig_property(_sofaswig.iauASTROM_ypl_get, _sofaswig.iauASTROM_ypl_set)
    __swig_setmethods__["sphi"] = _sofaswig.iauASTROM_sphi_set
    __swig_getmethods__["sphi"] = _sofaswig.iauASTROM_sphi_get
    if _newclass:sphi = _swig_property(_sofaswig.iauASTROM_sphi_get, _sofaswig.iauASTROM_sphi_set)
    __swig_setmethods__["cphi"] = _sofaswig.iauASTROM_cphi_set
    __swig_getmethods__["cphi"] = _sofaswig.iauASTROM_cphi_get
    if _newclass:cphi = _swig_property(_sofaswig.iauASTROM_cphi_get, _sofaswig.iauASTROM_cphi_set)
    __swig_setmethods__["diurab"] = _sofaswig.iauASTROM_diurab_set
    __swig_getmethods__["diurab"] = _sofaswig.iauASTROM_diurab_get
    if _newclass:diurab = _swig_property(_sofaswig.iauASTROM_diurab_get, _sofaswig.iauASTROM_diurab_set)
    __swig_setmethods__["eral"] = _sofaswig.iauASTROM_eral_set
    __swig_getmethods__["eral"] = _sofaswig.iauASTROM_eral_get
    if _newclass:eral = _swig_property(_sofaswig.iauASTROM_eral_get, _sofaswig.iauASTROM_eral_set)
    __swig_setmethods__["refa"] = _sofaswig.iauASTROM_refa_set
    __swig_getmethods__["refa"] = _sofaswig.iauASTROM_refa_get
    if _newclass:refa = _swig_property(_sofaswig.iauASTROM_refa_get, _sofaswig.iauASTROM_refa_set)
    __swig_setmethods__["refb"] = _sofaswig.iauASTROM_refb_set
    __swig_getmethods__["refb"] = _sofaswig.iauASTROM_refb_get
    if _newclass:refb = _swig_property(_sofaswig.iauASTROM_refb_get, _sofaswig.iauASTROM_refb_set)
    def __init__(self): 
        this = _sofaswig.new_iauASTROM()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sofaswig.delete_iauASTROM
    __del__ = lambda self : None;
iauASTROM_swigregister = _sofaswig.iauASTROM_swigregister
iauASTROM_swigregister(iauASTROM)

class iauLDBODY(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, iauLDBODY, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, iauLDBODY, name)
    __repr__ = _swig_repr
    __swig_setmethods__["bm"] = _sofaswig.iauLDBODY_bm_set
    __swig_getmethods__["bm"] = _sofaswig.iauLDBODY_bm_get
    if _newclass:bm = _swig_property(_sofaswig.iauLDBODY_bm_get, _sofaswig.iauLDBODY_bm_set)
    __swig_setmethods__["dl"] = _sofaswig.iauLDBODY_dl_set
    __swig_getmethods__["dl"] = _sofaswig.iauLDBODY_dl_get
    if _newclass:dl = _swig_property(_sofaswig.iauLDBODY_dl_get, _sofaswig.iauLDBODY_dl_set)
    __swig_setmethods__["pv"] = _sofaswig.iauLDBODY_pv_set
    __swig_getmethods__["pv"] = _sofaswig.iauLDBODY_pv_get
    if _newclass:pv = _swig_property(_sofaswig.iauLDBODY_pv_get, _sofaswig.iauLDBODY_pv_set)
    def __init__(self): 
        this = _sofaswig.new_iauLDBODY()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sofaswig.delete_iauLDBODY
    __del__ = lambda self : None;
iauLDBODY_swigregister = _sofaswig.iauLDBODY_swigregister
iauLDBODY_swigregister(iauLDBODY)

DPI = _sofaswig.DPI
D2PI = _sofaswig.D2PI
DR2D = _sofaswig.DR2D
DD2R = _sofaswig.DD2R
DR2AS = _sofaswig.DR2AS
DAS2R = _sofaswig.DAS2R
DS2R = _sofaswig.DS2R
TURNAS = _sofaswig.TURNAS
DMAS2R = _sofaswig.DMAS2R
DTY = _sofaswig.DTY
DAYSEC = _sofaswig.DAYSEC
DJY = _sofaswig.DJY
DJC = _sofaswig.DJC
DJM = _sofaswig.DJM
DJ00 = _sofaswig.DJ00
DJM0 = _sofaswig.DJM0
DJM00 = _sofaswig.DJM00
DJM77 = _sofaswig.DJM77
TTMTAI = _sofaswig.TTMTAI
DAU = _sofaswig.DAU
CMPS = _sofaswig.CMPS
AULT = _sofaswig.AULT
DC = _sofaswig.DC
ELG = _sofaswig.ELG
ELB = _sofaswig.ELB
TDB0 = _sofaswig.TDB0
SRS = _sofaswig.SRS
WGS84 = _sofaswig.WGS84
GRS80 = _sofaswig.GRS80
WGS72 = _sofaswig.WGS72

def iauCal2jd(*args):
  return _sofaswig.iauCal2jd(*args)
iauCal2jd = _sofaswig.iauCal2jd

def iauEpb(*args):
  return _sofaswig.iauEpb(*args)
iauEpb = _sofaswig.iauEpb

def iauEpb2jd(*args):
  return _sofaswig.iauEpb2jd(*args)
iauEpb2jd = _sofaswig.iauEpb2jd

def iauEpj(*args):
  return _sofaswig.iauEpj(*args)
iauEpj = _sofaswig.iauEpj

def iauEpj2jd(*args):
  return _sofaswig.iauEpj2jd(*args)
iauEpj2jd = _sofaswig.iauEpj2jd

def iauJd2cal(*args):
  return _sofaswig.iauJd2cal(*args)
iauJd2cal = _sofaswig.iauJd2cal

def iauJdcalf(*args):
  return _sofaswig.iauJdcalf(*args)
iauJdcalf = _sofaswig.iauJdcalf

def iauAb(*args):
  return _sofaswig.iauAb(*args)
iauAb = _sofaswig.iauAb

def iauApcg(*args):
  return _sofaswig.iauApcg(*args)
iauApcg = _sofaswig.iauApcg

def iauApcg13(*args):
  return _sofaswig.iauApcg13(*args)
iauApcg13 = _sofaswig.iauApcg13

def iauApci(*args):
  return _sofaswig.iauApci(*args)
iauApci = _sofaswig.iauApci

def iauApci13(*args):
  return _sofaswig.iauApci13(*args)
iauApci13 = _sofaswig.iauApci13

def iauApco(*args):
  return _sofaswig.iauApco(*args)
iauApco = _sofaswig.iauApco

def iauApco13(*args):
  return _sofaswig.iauApco13(*args)
iauApco13 = _sofaswig.iauApco13

def iauApcs(*args):
  return _sofaswig.iauApcs(*args)
iauApcs = _sofaswig.iauApcs

def iauApcs13(*args):
  return _sofaswig.iauApcs13(*args)
iauApcs13 = _sofaswig.iauApcs13

def iauAper(*args):
  return _sofaswig.iauAper(*args)
iauAper = _sofaswig.iauAper

def iauAper13(*args):
  return _sofaswig.iauAper13(*args)
iauAper13 = _sofaswig.iauAper13

def iauApio(*args):
  return _sofaswig.iauApio(*args)
iauApio = _sofaswig.iauApio

def iauApio13(*args):
  return _sofaswig.iauApio13(*args)
iauApio13 = _sofaswig.iauApio13

def iauAtci13(*args):
  return _sofaswig.iauAtci13(*args)
iauAtci13 = _sofaswig.iauAtci13

def iauAtciq(*args):
  return _sofaswig.iauAtciq(*args)
iauAtciq = _sofaswig.iauAtciq

def iauAtciqn(*args):
  return _sofaswig.iauAtciqn(*args)
iauAtciqn = _sofaswig.iauAtciqn

def iauAtciqz(*args):
  return _sofaswig.iauAtciqz(*args)
iauAtciqz = _sofaswig.iauAtciqz

def iauAtco13(*args):
  return _sofaswig.iauAtco13(*args)
iauAtco13 = _sofaswig.iauAtco13

def iauAtic13(*args):
  return _sofaswig.iauAtic13(*args)
iauAtic13 = _sofaswig.iauAtic13

def iauAticq(*args):
  return _sofaswig.iauAticq(*args)
iauAticq = _sofaswig.iauAticq

def iauAticqn(*args):
  return _sofaswig.iauAticqn(*args)
iauAticqn = _sofaswig.iauAticqn

def iauAtio13(*args):
  return _sofaswig.iauAtio13(*args)
iauAtio13 = _sofaswig.iauAtio13

def iauAtioq(*args):
  return _sofaswig.iauAtioq(*args)
iauAtioq = _sofaswig.iauAtioq

def iauAtoc13(*args):
  return _sofaswig.iauAtoc13(*args)
iauAtoc13 = _sofaswig.iauAtoc13

def iauAtoi13(*args):
  return _sofaswig.iauAtoi13(*args)
iauAtoi13 = _sofaswig.iauAtoi13

def iauAtoiq(*args):
  return _sofaswig.iauAtoiq(*args)
iauAtoiq = _sofaswig.iauAtoiq

def iauLd(*args):
  return _sofaswig.iauLd(*args)
iauLd = _sofaswig.iauLd

def iauLdn(*args):
  return _sofaswig.iauLdn(*args)
iauLdn = _sofaswig.iauLdn

def iauLdsun(*args):
  return _sofaswig.iauLdsun(*args)
iauLdsun = _sofaswig.iauLdsun

def iauPmpx(*args):
  return _sofaswig.iauPmpx(*args)
iauPmpx = _sofaswig.iauPmpx

def iauPmsafe(*args):
  return _sofaswig.iauPmsafe(*args)
iauPmsafe = _sofaswig.iauPmsafe

def iauPvtob(*args):
  return _sofaswig.iauPvtob(*args)
iauPvtob = _sofaswig.iauPvtob

def iauRefco(*args):
  return _sofaswig.iauRefco(*args)
iauRefco = _sofaswig.iauRefco

def iauEpv00(*args):
  return _sofaswig.iauEpv00(*args)
iauEpv00 = _sofaswig.iauEpv00

def iauPlan94(*args):
  return _sofaswig.iauPlan94(*args)
iauPlan94 = _sofaswig.iauPlan94

def iauFad03(*args):
  return _sofaswig.iauFad03(*args)
iauFad03 = _sofaswig.iauFad03

def iauFae03(*args):
  return _sofaswig.iauFae03(*args)
iauFae03 = _sofaswig.iauFae03

def iauFaf03(*args):
  return _sofaswig.iauFaf03(*args)
iauFaf03 = _sofaswig.iauFaf03

def iauFaju03(*args):
  return _sofaswig.iauFaju03(*args)
iauFaju03 = _sofaswig.iauFaju03

def iauFal03(*args):
  return _sofaswig.iauFal03(*args)
iauFal03 = _sofaswig.iauFal03

def iauFalp03(*args):
  return _sofaswig.iauFalp03(*args)
iauFalp03 = _sofaswig.iauFalp03

def iauFama03(*args):
  return _sofaswig.iauFama03(*args)
iauFama03 = _sofaswig.iauFama03

def iauFame03(*args):
  return _sofaswig.iauFame03(*args)
iauFame03 = _sofaswig.iauFame03

def iauFane03(*args):
  return _sofaswig.iauFane03(*args)
iauFane03 = _sofaswig.iauFane03

def iauFaom03(*args):
  return _sofaswig.iauFaom03(*args)
iauFaom03 = _sofaswig.iauFaom03

def iauFapa03(*args):
  return _sofaswig.iauFapa03(*args)
iauFapa03 = _sofaswig.iauFapa03

def iauFasa03(*args):
  return _sofaswig.iauFasa03(*args)
iauFasa03 = _sofaswig.iauFasa03

def iauFaur03(*args):
  return _sofaswig.iauFaur03(*args)
iauFaur03 = _sofaswig.iauFaur03

def iauFave03(*args):
  return _sofaswig.iauFave03(*args)
iauFave03 = _sofaswig.iauFave03

def iauBi00(*args):
  return _sofaswig.iauBi00(*args)
iauBi00 = _sofaswig.iauBi00

def iauBp00(*args):
  return _sofaswig.iauBp00(*args)
iauBp00 = _sofaswig.iauBp00

def iauBp06(*args):
  return _sofaswig.iauBp06(*args)
iauBp06 = _sofaswig.iauBp06

def iauBpn2xy(*args):
  return _sofaswig.iauBpn2xy(*args)
iauBpn2xy = _sofaswig.iauBpn2xy

def iauC2i00a(*args):
  return _sofaswig.iauC2i00a(*args)
iauC2i00a = _sofaswig.iauC2i00a

def iauC2i00b(*args):
  return _sofaswig.iauC2i00b(*args)
iauC2i00b = _sofaswig.iauC2i00b

def iauC2i06a(*args):
  return _sofaswig.iauC2i06a(*args)
iauC2i06a = _sofaswig.iauC2i06a

def iauC2ibpn(*args):
  return _sofaswig.iauC2ibpn(*args)
iauC2ibpn = _sofaswig.iauC2ibpn

def iauC2ixy(*args):
  return _sofaswig.iauC2ixy(*args)
iauC2ixy = _sofaswig.iauC2ixy

def iauC2ixys(*args):
  return _sofaswig.iauC2ixys(*args)
iauC2ixys = _sofaswig.iauC2ixys

def iauC2t00a(*args):
  return _sofaswig.iauC2t00a(*args)
iauC2t00a = _sofaswig.iauC2t00a

def iauC2t00b(*args):
  return _sofaswig.iauC2t00b(*args)
iauC2t00b = _sofaswig.iauC2t00b

def iauC2t06a(*args):
  return _sofaswig.iauC2t06a(*args)
iauC2t06a = _sofaswig.iauC2t06a

def iauC2tcio(*args):
  return _sofaswig.iauC2tcio(*args)
iauC2tcio = _sofaswig.iauC2tcio

def iauC2teqx(*args):
  return _sofaswig.iauC2teqx(*args)
iauC2teqx = _sofaswig.iauC2teqx

def iauC2tpe(*args):
  return _sofaswig.iauC2tpe(*args)
iauC2tpe = _sofaswig.iauC2tpe

def iauC2txy(*args):
  return _sofaswig.iauC2txy(*args)
iauC2txy = _sofaswig.iauC2txy

def iauEo06a(*args):
  return _sofaswig.iauEo06a(*args)
iauEo06a = _sofaswig.iauEo06a

def iauEors(*args):
  return _sofaswig.iauEors(*args)
iauEors = _sofaswig.iauEors

def iauFw2m(*args):
  return _sofaswig.iauFw2m(*args)
iauFw2m = _sofaswig.iauFw2m

def iauFw2xy(*args):
  return _sofaswig.iauFw2xy(*args)
iauFw2xy = _sofaswig.iauFw2xy

def iauLtp(*args):
  return _sofaswig.iauLtp(*args)
iauLtp = _sofaswig.iauLtp

def iauLtpb(*args):
  return _sofaswig.iauLtpb(*args)
iauLtpb = _sofaswig.iauLtpb

def iauLtpecl(*args):
  return _sofaswig.iauLtpecl(*args)
iauLtpecl = _sofaswig.iauLtpecl

def iauLtpequ(*args):
  return _sofaswig.iauLtpequ(*args)
iauLtpequ = _sofaswig.iauLtpequ

def iauNum00a(*args):
  return _sofaswig.iauNum00a(*args)
iauNum00a = _sofaswig.iauNum00a

def iauNum00b(*args):
  return _sofaswig.iauNum00b(*args)
iauNum00b = _sofaswig.iauNum00b

def iauNum06a(*args):
  return _sofaswig.iauNum06a(*args)
iauNum06a = _sofaswig.iauNum06a

def iauNumat(*args):
  return _sofaswig.iauNumat(*args)
iauNumat = _sofaswig.iauNumat

def iauNut00a(*args):
  return _sofaswig.iauNut00a(*args)
iauNut00a = _sofaswig.iauNut00a

def iauNut00b(*args):
  return _sofaswig.iauNut00b(*args)
iauNut00b = _sofaswig.iauNut00b

def iauNut06a(*args):
  return _sofaswig.iauNut06a(*args)
iauNut06a = _sofaswig.iauNut06a

def iauNut80(*args):
  return _sofaswig.iauNut80(*args)
iauNut80 = _sofaswig.iauNut80

def iauNutm80(*args):
  return _sofaswig.iauNutm80(*args)
iauNutm80 = _sofaswig.iauNutm80

def iauObl06(*args):
  return _sofaswig.iauObl06(*args)
iauObl06 = _sofaswig.iauObl06

def iauObl80(*args):
  return _sofaswig.iauObl80(*args)
iauObl80 = _sofaswig.iauObl80

def iauP06e(*args):
  return _sofaswig.iauP06e(*args)
iauP06e = _sofaswig.iauP06e

def iauPb06(*args):
  return _sofaswig.iauPb06(*args)
iauPb06 = _sofaswig.iauPb06

def iauPfw06(*args):
  return _sofaswig.iauPfw06(*args)
iauPfw06 = _sofaswig.iauPfw06

def iauPmat00(*args):
  return _sofaswig.iauPmat00(*args)
iauPmat00 = _sofaswig.iauPmat00

def iauPmat06(*args):
  return _sofaswig.iauPmat06(*args)
iauPmat06 = _sofaswig.iauPmat06

def iauPmat76(*args):
  return _sofaswig.iauPmat76(*args)
iauPmat76 = _sofaswig.iauPmat76

def iauPn00(*args):
  return _sofaswig.iauPn00(*args)
iauPn00 = _sofaswig.iauPn00

def iauPn00a(*args):
  return _sofaswig.iauPn00a(*args)
iauPn00a = _sofaswig.iauPn00a

def iauPn00b(*args):
  return _sofaswig.iauPn00b(*args)
iauPn00b = _sofaswig.iauPn00b

def iauPn06(*args):
  return _sofaswig.iauPn06(*args)
iauPn06 = _sofaswig.iauPn06

def iauPn06a(*args):
  return _sofaswig.iauPn06a(*args)
iauPn06a = _sofaswig.iauPn06a

def iauPnm00a(*args):
  return _sofaswig.iauPnm00a(*args)
iauPnm00a = _sofaswig.iauPnm00a

def iauPnm00b(*args):
  return _sofaswig.iauPnm00b(*args)
iauPnm00b = _sofaswig.iauPnm00b

def iauPnm06a(*args):
  return _sofaswig.iauPnm06a(*args)
iauPnm06a = _sofaswig.iauPnm06a

def iauPnm80(*args):
  return _sofaswig.iauPnm80(*args)
iauPnm80 = _sofaswig.iauPnm80

def iauPom00(*args):
  return _sofaswig.iauPom00(*args)
iauPom00 = _sofaswig.iauPom00

def iauPr00(*args):
  return _sofaswig.iauPr00(*args)
iauPr00 = _sofaswig.iauPr00

def iauPrec76(*args):
  return _sofaswig.iauPrec76(*args)
iauPrec76 = _sofaswig.iauPrec76

def iauS00(*args):
  return _sofaswig.iauS00(*args)
iauS00 = _sofaswig.iauS00

def iauS00a(*args):
  return _sofaswig.iauS00a(*args)
iauS00a = _sofaswig.iauS00a

def iauS00b(*args):
  return _sofaswig.iauS00b(*args)
iauS00b = _sofaswig.iauS00b

def iauS06(*args):
  return _sofaswig.iauS06(*args)
iauS06 = _sofaswig.iauS06

def iauS06a(*args):
  return _sofaswig.iauS06a(*args)
iauS06a = _sofaswig.iauS06a

def iauSp00(*args):
  return _sofaswig.iauSp00(*args)
iauSp00 = _sofaswig.iauSp00

def iauXy06(*args):
  return _sofaswig.iauXy06(*args)
iauXy06 = _sofaswig.iauXy06

def iauXys00a(*args):
  return _sofaswig.iauXys00a(*args)
iauXys00a = _sofaswig.iauXys00a

def iauXys00b(*args):
  return _sofaswig.iauXys00b(*args)
iauXys00b = _sofaswig.iauXys00b

def iauXys06a(*args):
  return _sofaswig.iauXys06a(*args)
iauXys06a = _sofaswig.iauXys06a

def iauEe00(*args):
  return _sofaswig.iauEe00(*args)
iauEe00 = _sofaswig.iauEe00

def iauEe00a(*args):
  return _sofaswig.iauEe00a(*args)
iauEe00a = _sofaswig.iauEe00a

def iauEe00b(*args):
  return _sofaswig.iauEe00b(*args)
iauEe00b = _sofaswig.iauEe00b

def iauEe06a(*args):
  return _sofaswig.iauEe06a(*args)
iauEe06a = _sofaswig.iauEe06a

def iauEect00(*args):
  return _sofaswig.iauEect00(*args)
iauEect00 = _sofaswig.iauEect00

def iauEqeq94(*args):
  return _sofaswig.iauEqeq94(*args)
iauEqeq94 = _sofaswig.iauEqeq94

def iauEra00(*args):
  return _sofaswig.iauEra00(*args)
iauEra00 = _sofaswig.iauEra00

def iauGmst00(*args):
  return _sofaswig.iauGmst00(*args)
iauGmst00 = _sofaswig.iauGmst00

def iauGmst06(*args):
  return _sofaswig.iauGmst06(*args)
iauGmst06 = _sofaswig.iauGmst06

def iauGmst82(*args):
  return _sofaswig.iauGmst82(*args)
iauGmst82 = _sofaswig.iauGmst82

def iauGst00a(*args):
  return _sofaswig.iauGst00a(*args)
iauGst00a = _sofaswig.iauGst00a

def iauGst00b(*args):
  return _sofaswig.iauGst00b(*args)
iauGst00b = _sofaswig.iauGst00b

def iauGst06(*args):
  return _sofaswig.iauGst06(*args)
iauGst06 = _sofaswig.iauGst06

def iauGst06a(*args):
  return _sofaswig.iauGst06a(*args)
iauGst06a = _sofaswig.iauGst06a

def iauGst94(*args):
  return _sofaswig.iauGst94(*args)
iauGst94 = _sofaswig.iauGst94

def iauPvstar(*args):
  return _sofaswig.iauPvstar(*args)
iauPvstar = _sofaswig.iauPvstar

def iauStarpv(*args):
  return _sofaswig.iauStarpv(*args)
iauStarpv = _sofaswig.iauStarpv

def iauFk52h(*args):
  return _sofaswig.iauFk52h(*args)
iauFk52h = _sofaswig.iauFk52h

def iauFk5hip(*args):
  return _sofaswig.iauFk5hip(*args)
iauFk5hip = _sofaswig.iauFk5hip

def iauFk5hz(*args):
  return _sofaswig.iauFk5hz(*args)
iauFk5hz = _sofaswig.iauFk5hz

def iauH2fk5(*args):
  return _sofaswig.iauH2fk5(*args)
iauH2fk5 = _sofaswig.iauH2fk5

def iauHfk5z(*args):
  return _sofaswig.iauHfk5z(*args)
iauHfk5z = _sofaswig.iauHfk5z

def iauStarpm(*args):
  return _sofaswig.iauStarpm(*args)
iauStarpm = _sofaswig.iauStarpm

def iauEceq06(*args):
  return _sofaswig.iauEceq06(*args)
iauEceq06 = _sofaswig.iauEceq06

def iauEcm06(*args):
  return _sofaswig.iauEcm06(*args)
iauEcm06 = _sofaswig.iauEcm06

def iauEqec06(*args):
  return _sofaswig.iauEqec06(*args)
iauEqec06 = _sofaswig.iauEqec06

def iauLteceq(*args):
  return _sofaswig.iauLteceq(*args)
iauLteceq = _sofaswig.iauLteceq

def iauLtecm(*args):
  return _sofaswig.iauLtecm(*args)
iauLtecm = _sofaswig.iauLtecm

def iauLteqec(*args):
  return _sofaswig.iauLteqec(*args)
iauLteqec = _sofaswig.iauLteqec

def iauG2icrs(*args):
  return _sofaswig.iauG2icrs(*args)
iauG2icrs = _sofaswig.iauG2icrs

def iauIcrs2g(*args):
  return _sofaswig.iauIcrs2g(*args)
iauIcrs2g = _sofaswig.iauIcrs2g

def iauEform(*args):
  return _sofaswig.iauEform(*args)
iauEform = _sofaswig.iauEform

def iauGc2gd(*args):
  return _sofaswig.iauGc2gd(*args)
iauGc2gd = _sofaswig.iauGc2gd

def iauGc2gde(*args):
  return _sofaswig.iauGc2gde(*args)
iauGc2gde = _sofaswig.iauGc2gde

def iauGd2gc(*args):
  return _sofaswig.iauGd2gc(*args)
iauGd2gc = _sofaswig.iauGd2gc

def iauGd2gce(*args):
  return _sofaswig.iauGd2gce(*args)
iauGd2gce = _sofaswig.iauGd2gce

def iauD2dtf(*args):
  return _sofaswig.iauD2dtf(*args)
iauD2dtf = _sofaswig.iauD2dtf

def iauDat(*args):
  return _sofaswig.iauDat(*args)
iauDat = _sofaswig.iauDat

def iauDtdb(*args):
  return _sofaswig.iauDtdb(*args)
iauDtdb = _sofaswig.iauDtdb

def iauDtf2d(*args):
  return _sofaswig.iauDtf2d(*args)
iauDtf2d = _sofaswig.iauDtf2d

def iauTaitt(*args):
  return _sofaswig.iauTaitt(*args)
iauTaitt = _sofaswig.iauTaitt

def iauTaiut1(*args):
  return _sofaswig.iauTaiut1(*args)
iauTaiut1 = _sofaswig.iauTaiut1

def iauTaiutc(*args):
  return _sofaswig.iauTaiutc(*args)
iauTaiutc = _sofaswig.iauTaiutc

def iauTcbtdb(*args):
  return _sofaswig.iauTcbtdb(*args)
iauTcbtdb = _sofaswig.iauTcbtdb

def iauTcgtt(*args):
  return _sofaswig.iauTcgtt(*args)
iauTcgtt = _sofaswig.iauTcgtt

def iauTdbtcb(*args):
  return _sofaswig.iauTdbtcb(*args)
iauTdbtcb = _sofaswig.iauTdbtcb

def iauTdbtt(*args):
  return _sofaswig.iauTdbtt(*args)
iauTdbtt = _sofaswig.iauTdbtt

def iauTttai(*args):
  return _sofaswig.iauTttai(*args)
iauTttai = _sofaswig.iauTttai

def iauTttcg(*args):
  return _sofaswig.iauTttcg(*args)
iauTttcg = _sofaswig.iauTttcg

def iauTttdb(*args):
  return _sofaswig.iauTttdb(*args)
iauTttdb = _sofaswig.iauTttdb

def iauTtut1(*args):
  return _sofaswig.iauTtut1(*args)
iauTtut1 = _sofaswig.iauTtut1

def iauUt1tai(*args):
  return _sofaswig.iauUt1tai(*args)
iauUt1tai = _sofaswig.iauUt1tai

def iauUt1tt(*args):
  return _sofaswig.iauUt1tt(*args)
iauUt1tt = _sofaswig.iauUt1tt

def iauUt1utc(*args):
  return _sofaswig.iauUt1utc(*args)
iauUt1utc = _sofaswig.iauUt1utc

def iauUtctai(*args):
  return _sofaswig.iauUtctai(*args)
iauUtctai = _sofaswig.iauUtctai

def iauUtcut1(*args):
  return _sofaswig.iauUtcut1(*args)
iauUtcut1 = _sofaswig.iauUtcut1

def iauAe2hd(*args):
  return _sofaswig.iauAe2hd(*args)
iauAe2hd = _sofaswig.iauAe2hd

def iauHd2ae(*args):
  return _sofaswig.iauHd2ae(*args)
iauHd2ae = _sofaswig.iauHd2ae

def iauHd2pa(*args):
  return _sofaswig.iauHd2pa(*args)
iauHd2pa = _sofaswig.iauHd2pa

def iauTpors(*args):
  return _sofaswig.iauTpors(*args)
iauTpors = _sofaswig.iauTpors

def iauTporv(*args):
  return _sofaswig.iauTporv(*args)
iauTporv = _sofaswig.iauTporv

def iauTpsts(*args):
  return _sofaswig.iauTpsts(*args)
iauTpsts = _sofaswig.iauTpsts

def iauTpstv(*args):
  return _sofaswig.iauTpstv(*args)
iauTpstv = _sofaswig.iauTpstv

def iauTpxes(*args):
  return _sofaswig.iauTpxes(*args)
iauTpxes = _sofaswig.iauTpxes

def iauTpxev(*args):
  return _sofaswig.iauTpxev(*args)
iauTpxev = _sofaswig.iauTpxev

def iauA2af(*args):
  return _sofaswig.iauA2af(*args)
iauA2af = _sofaswig.iauA2af

def iauA2tf(*args):
  return _sofaswig.iauA2tf(*args)
iauA2tf = _sofaswig.iauA2tf

def iauAf2a(*args):
  return _sofaswig.iauAf2a(*args)
iauAf2a = _sofaswig.iauAf2a

def iauAnp(*args):
  return _sofaswig.iauAnp(*args)
iauAnp = _sofaswig.iauAnp

def iauAnpm(*args):
  return _sofaswig.iauAnpm(*args)
iauAnpm = _sofaswig.iauAnpm

def iauD2tf(*args):
  return _sofaswig.iauD2tf(*args)
iauD2tf = _sofaswig.iauD2tf

def iauTf2a(*args):
  return _sofaswig.iauTf2a(*args)
iauTf2a = _sofaswig.iauTf2a

def iauTf2d(*args):
  return _sofaswig.iauTf2d(*args)
iauTf2d = _sofaswig.iauTf2d

def iauRx(*args):
  return _sofaswig.iauRx(*args)
iauRx = _sofaswig.iauRx

def iauRy(*args):
  return _sofaswig.iauRy(*args)
iauRy = _sofaswig.iauRy

def iauRz(*args):
  return _sofaswig.iauRz(*args)
iauRz = _sofaswig.iauRz

def iauCp(*args):
  return _sofaswig.iauCp(*args)
iauCp = _sofaswig.iauCp

def iauCpv(*args):
  return _sofaswig.iauCpv(*args)
iauCpv = _sofaswig.iauCpv

def iauCr(*args):
  return _sofaswig.iauCr(*args)
iauCr = _sofaswig.iauCr

def iauP2pv(*args):
  return _sofaswig.iauP2pv(*args)
iauP2pv = _sofaswig.iauP2pv

def iauPv2p(*args):
  return _sofaswig.iauPv2p(*args)
iauPv2p = _sofaswig.iauPv2p

def iauIr(*args):
  return _sofaswig.iauIr(*args)
iauIr = _sofaswig.iauIr

def iauZp(*args):
  return _sofaswig.iauZp(*args)
iauZp = _sofaswig.iauZp

def iauZpv(*args):
  return _sofaswig.iauZpv(*args)
iauZpv = _sofaswig.iauZpv

def iauZr(*args):
  return _sofaswig.iauZr(*args)
iauZr = _sofaswig.iauZr

def iauRxr(*args):
  return _sofaswig.iauRxr(*args)
iauRxr = _sofaswig.iauRxr

def iauTr(*args):
  return _sofaswig.iauTr(*args)
iauTr = _sofaswig.iauTr

def iauRxp(*args):
  return _sofaswig.iauRxp(*args)
iauRxp = _sofaswig.iauRxp

def iauRxpv(*args):
  return _sofaswig.iauRxpv(*args)
iauRxpv = _sofaswig.iauRxpv

def iauTrxp(*args):
  return _sofaswig.iauTrxp(*args)
iauTrxp = _sofaswig.iauTrxp

def iauTrxpv(*args):
  return _sofaswig.iauTrxpv(*args)
iauTrxpv = _sofaswig.iauTrxpv

def iauRm2v(*args):
  return _sofaswig.iauRm2v(*args)
iauRm2v = _sofaswig.iauRm2v

def iauRv2m(*args):
  return _sofaswig.iauRv2m(*args)
iauRv2m = _sofaswig.iauRv2m

def iauPap(*args):
  return _sofaswig.iauPap(*args)
iauPap = _sofaswig.iauPap

def iauPas(*args):
  return _sofaswig.iauPas(*args)
iauPas = _sofaswig.iauPas

def iauSepp(*args):
  return _sofaswig.iauSepp(*args)
iauSepp = _sofaswig.iauSepp

def iauSeps(*args):
  return _sofaswig.iauSeps(*args)
iauSeps = _sofaswig.iauSeps

def iauC2s(*args):
  return _sofaswig.iauC2s(*args)
iauC2s = _sofaswig.iauC2s

def iauP2s(*args):
  return _sofaswig.iauP2s(*args)
iauP2s = _sofaswig.iauP2s

def iauPv2s(*args):
  return _sofaswig.iauPv2s(*args)
iauPv2s = _sofaswig.iauPv2s

def iauS2c(*args):
  return _sofaswig.iauS2c(*args)
iauS2c = _sofaswig.iauS2c

def iauS2p(*args):
  return _sofaswig.iauS2p(*args)
iauS2p = _sofaswig.iauS2p

def iauS2pv(*args):
  return _sofaswig.iauS2pv(*args)
iauS2pv = _sofaswig.iauS2pv

def iauPdp(*args):
  return _sofaswig.iauPdp(*args)
iauPdp = _sofaswig.iauPdp

def iauPm(*args):
  return _sofaswig.iauPm(*args)
iauPm = _sofaswig.iauPm

def iauPmp(*args):
  return _sofaswig.iauPmp(*args)
iauPmp = _sofaswig.iauPmp

def iauPn(*args):
  return _sofaswig.iauPn(*args)
iauPn = _sofaswig.iauPn

def iauPpp(*args):
  return _sofaswig.iauPpp(*args)
iauPpp = _sofaswig.iauPpp

def iauPpsp(*args):
  return _sofaswig.iauPpsp(*args)
iauPpsp = _sofaswig.iauPpsp

def iauPvdpv(*args):
  return _sofaswig.iauPvdpv(*args)
iauPvdpv = _sofaswig.iauPvdpv

def iauPvm(*args):
  return _sofaswig.iauPvm(*args)
iauPvm = _sofaswig.iauPvm

def iauPvmpv(*args):
  return _sofaswig.iauPvmpv(*args)
iauPvmpv = _sofaswig.iauPvmpv

def iauPvppv(*args):
  return _sofaswig.iauPvppv(*args)
iauPvppv = _sofaswig.iauPvppv

def iauPvu(*args):
  return _sofaswig.iauPvu(*args)
iauPvu = _sofaswig.iauPvu

def iauPvup(*args):
  return _sofaswig.iauPvup(*args)
iauPvup = _sofaswig.iauPvup

def iauPvxpv(*args):
  return _sofaswig.iauPvxpv(*args)
iauPvxpv = _sofaswig.iauPvxpv

def iauPxp(*args):
  return _sofaswig.iauPxp(*args)
iauPxp = _sofaswig.iauPxp

def iauS2xpv(*args):
  return _sofaswig.iauS2xpv(*args)
iauS2xpv = _sofaswig.iauS2xpv

def iauSxp(*args):
  return _sofaswig.iauSxp(*args)
iauSxp = _sofaswig.iauSxp

def iauSxpv(*args):
  return _sofaswig.iauSxpv(*args)
iauSxpv = _sofaswig.iauSxpv

def reprd(*args):
  return _sofaswig.reprd(*args)
reprd = _sofaswig.reprd

def Createint():
  return _sofaswig.Createint()
Createint = _sofaswig.Createint

def Setint(*args):
  return _sofaswig.Setint(*args)
Setint = _sofaswig.Setint

def Createchar():
  return _sofaswig.Createchar()
Createchar = _sofaswig.Createchar

def Getchar(*args):
  return _sofaswig.Getchar(*args)
Getchar = _sofaswig.Getchar

def Getdouble(*args):
  return _sofaswig.Getdouble(*args)
Getdouble = _sofaswig.Getdouble

def Create2DArray13():
  return _sofaswig.Create2DArray13()
Create2DArray13 = _sofaswig.Create2DArray13

def GetElem2DArray13(*args):
  return _sofaswig.GetElem2DArray13(*args)
GetElem2DArray13 = _sofaswig.GetElem2DArray13

def SetElem2DArray13(*args):
  return _sofaswig.SetElem2DArray13(*args)
SetElem2DArray13 = _sofaswig.SetElem2DArray13

def Create2DArray23():
  return _sofaswig.Create2DArray23()
Create2DArray23 = _sofaswig.Create2DArray23

def GetElem2DArray23(*args):
  return _sofaswig.GetElem2DArray23(*args)
GetElem2DArray23 = _sofaswig.GetElem2DArray23

def SetElem2DArray23(*args):
  return _sofaswig.SetElem2DArray23(*args)
SetElem2DArray23 = _sofaswig.SetElem2DArray23

def Create2DArray33():
  return _sofaswig.Create2DArray33()
Create2DArray33 = _sofaswig.Create2DArray33

def GetElem2DArray33(*args):
  return _sofaswig.GetElem2DArray33(*args)
GetElem2DArray33 = _sofaswig.GetElem2DArray33

def SetElem2DArray33(*args):
  return _sofaswig.SetElem2DArray33(*args)
SetElem2DArray33 = _sofaswig.SetElem2DArray33

def iauLdbn():
  return _sofaswig.iauLdbn()
iauLdbn = _sofaswig.iauLdbn

def iauLdbnB3():
  return _sofaswig.iauLdbnB3()
iauLdbnB3 = _sofaswig.iauLdbnB3

def SetiauLDBODY(*args):
  return _sofaswig.SetiauLDBODY(*args)
SetiauLDBODY = _sofaswig.SetiauLDBODY

def GetiauLDBODY(*args):
  return _sofaswig.GetiauLDBODY(*args)
GetiauLDBODY = _sofaswig.GetiauLDBODY
class SOFA(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SOFA, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SOFA, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _sofaswig.new_SOFA()
        try: self.this.append(this)
        except: self.this = this
    def SetSite(self, *args): return _sofaswig.SOFA_SetSite(self, *args)
    def PrintSite(self): return _sofaswig.SOFA_PrintSite(self)
    def SetSiteCondition(self, *args): return _sofaswig.SOFA_SetSiteCondition(self, *args)
    def PrintSSC(self): return _sofaswig.SOFA_PrintSSC(self)
    def CurrentTimeInit(self): return _sofaswig.SOFA_CurrentTimeInit(self)
    def SetTime(self): return _sofaswig.SOFA_SetTime(self)
    def InputTime(self, *args): return _sofaswig.SOFA_InputTime(self, *args)
    def PrintTime(self): return _sofaswig.SOFA_PrintTime(self)
    def PrintInputTime(self): return _sofaswig.SOFA_PrintInputTime(self)
    def JulianDate_UTC(self): return _sofaswig.SOFA_JulianDate_UTC(self)
    def GetTDB1(self): return _sofaswig.SOFA_GetTDB1(self)
    def GetTDB2(self): return _sofaswig.SOFA_GetTDB2(self)
    def GetJD1(self): return _sofaswig.SOFA_GetJD1(self)
    def GetJD2(self): return _sofaswig.SOFA_GetJD2(self)
    def PrintJDUTC(self): return _sofaswig.SOFA_PrintJDUTC(self)
    def TerrestrialTime(self): return _sofaswig.SOFA_TerrestrialTime(self)
    def PrintTT(self): return _sofaswig.SOFA_PrintTT(self)
    def CoordinateCorrection(self, *args): return _sofaswig.SOFA_CoordinateCorrection(self, *args)
    def PrintCooCor(self): return _sofaswig.SOFA_PrintCooCor(self)
    def ObservationCatalog(self, *args): return _sofaswig.SOFA_ObservationCatalog(self, *args)
    def PrintObsC(self): return _sofaswig.SOFA_PrintObsC(self)
    def ObsCorrection(self, *args): return _sofaswig.SOFA_ObsCorrection(self, *args)
    def PrintObsCor(self): return _sofaswig.SOFA_PrintObsCor(self)
    def TerrestialEphemeris(self, *args): return _sofaswig.SOFA_TerrestialEphemeris(self, *args)
    def Getaz(self): return _sofaswig.SOFA_Getaz(self)
    def Getel(self): return _sofaswig.SOFA_Getel(self)
    def CIP_CIO(self): return _sofaswig.SOFA_CIP_CIO(self)
    def PrintCIO(self): return _sofaswig.SOFA_PrintCIO(self)
    __swig_destroy__ = _sofaswig.delete_SOFA
    __del__ = lambda self : None;
SOFA_swigregister = _sofaswig.SOFA_swigregister
SOFA_swigregister(SOFA)

# This file is compatible with both classic and new-style classes.


