from enum import Enum

LOGGER_NAME = 'yn40mtcs'
HISTORY_VALUES_QUEUE_SIZE = 50

class STATE(Enum):
    ON=1
    OFF=2
    CLOSE=3
    OPEN=4
    INSERT=5
    EXTRACT=6
    IDLE=7
    MOVING=8
    STANDBY=9
    LIMIT=10
    TRACKAZEL=11
    TRACKRADEC=12
    FAULT=13
    INIT=14
    RUNNING=15
    ALARM=16
    DISABLE=17
    HEALTH=18
    ERROR=19
    POWEROFF=20
    QUERY=21
    STOP=22
    ACU_ERR=23
    UNKNOWN=24

STATE_NAMES = [None, "ON", "OFF", "CLOSE", "OPEN", "INSERT", "EXTRACT", "IDLE", "MOVING", "STANDBY", \
                "LIMIT", "TRACKAZEL", "TRACKRADEC", "FAULT", "INIT", "RUNNING", "ALARM", "DISABLE", \
                "HEALTH", "ERROR", "POWEROFF", "QUERY", "STOP", "ACU_ERR", "UNKNOWN"]